### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by oneilsh** [tarakc02/rbst#1]
Hey Tarak,

I'm happy to see my project was inspirational, actually I had hoped it would be! R needs these sorts of things I think, and a bst would be a great addition. 

For the backend of your structure, you might look into the pure functional red-black tree described in Okasaki's book. He describes it as easy to implement (I haven't tried) and fast in practice. Of course, it's balanced as well, which is a good feature for a recursive implementation when the call stack is limited. (Alternatively, you could go non-balanced in a safe way using loops as opposed to recursion.)

All the best,
~Shawn

**Comment by tarakc02** [comment]
Thanks! I picked up Okaski's book from the library last week, and just read through chapter 3 which includes the implementation of the red-black tree. It does look pretty straightforward, I'll give it a shot as soon as I have a free moment. 

And I agree. I had not heard of or thought about the possibility of persistent data structures before seeing your paper, but as soon as I did, it made so much sense, and seems like such a welcome addition to R.

**Comment by tarakc02** [comment]
The implementation is now a red-black tree. I ended up relying more on the implementation in Sedwick/Wayne (Algorithms, 4th Edition) than on the one in Okaski's book (which I ended up finding a little more complicated), noting the balancing functions (flip, rotate_left, rotate_right) only modify nodes on the search path during insert.
